### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by doronbehar** [muesli4/mpd-touch-screen-gui#10]
Hello!

What is the license of this software?

**Comment by muesli4** [comment]
Hi,

I haven't decided on it yet.  Is there some particular license you would need?  I was thinking about LGPL.

**Comment by doronbehar** [comment]
I don't have any preference, I'm using this software in my [project](https://gitlab.com/doronbehar/jukebox/). I'd also like to add this to [NixOS' packages collection](https://github.com/NixOS/nixpkgs).

**Comment by muesli4** [comment]
I added licenses for most files by using `reuse`.  When possible I fell back to `LGPL-3-or-later`, which is also the most restrictive license.  Thus you may use that.

* Is this sufficient for your use case?
* Would you let me release your changes as `LGPL-3-or-later`?  I would use your name for the copyright text, if that is ok.

I am sorry that it took so long.  All the best and good luck with your project!

**Comment by doronbehar** [comment]
> * Would you let me release your changes as `LGPL-3-or-later`?  I would use your name for the copyright text, if that is ok.

Yes of course. Just out of curiosity, why use so many different licenses together? I think usually a single `LICENSE` file at the root of the repository should suffice as well.

**Comment by muesli4** [comment]
> > * Would you let me release your changes as `LGPL-3-or-later`?  I would use your name for the copyright text, if that is ok.
> 
> Yes of course. Just out of curiosity, why use so many different licenses together? I think usually a single `LICENSE` file at the root of the repository should suffice as well.

I found the `reuse` tool and wanted to achieve conformity with the reuse specification (i.e. `reuse lint`).  For that every file needs to be under a license.

* I redistribute some boost m4 files.
* I redistribute Google Material Design icons under Apache 3.
* I wanted to use LGPL for most files but not impose the same license on configuration files.  (It is kind of weird to have it for configuration files, but it is what it is.)

That being said, it was reasonably simple to do this as the tool can add headers and license files, download licenses, etc.

**Comment by doronbehar** [comment]
> I found the [reuse](https://reuse.software/) tool

Cool! Thanks for your corporation.
