### ISSUE TITLE
libwtk-sdl2 not found on configure

### ISSUE THREAD

**Issue by elchmartin** [muesli4/mpd-touch-screen-gui#2]
hi!
I am trying to install this to my RPi.
`pi@RadioPi:~/mpd-touch-screen-gui $ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SDL2... yes
checking for SDL2_TTF... yes
checking for SDL2_IMG... yes
checking for LIBWTK_SDL2... no
configure: error: Package requirements (libwtk-sdl2) were not met:

No package 'libwtk-sdl2' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBWTK_SDL2_CFLAGS
and LIBWTK_SDL2_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
pi@RadioPi:~/mpd-touch-screen-gui $`

on your github here -> https://github.com/muesli4/libwtk-sdl2
I cannot see any way to install this.
sorry if I am being stupid ... and thank you for reading ;-)

**Comment by muesli4** [comment]
> I cannot see any way to install this.

The correct way to install this is similar to `mpd-touch-screen-gui`. You have to invoke `autoreconf -vfi` and then you can do `configure`, `make` and `make install` as usual.

I will add that to the description once I have time. I've you're using Archlinux (or ArchlinuxARM) then you can also use the PKGBUILD files provided in https://github.com/muesli4/archlinux-packages.

> sorry if I am being stupid ... and thank you for reading ;-)

You're not and thanks for trying. Let me know if you have any further issues.

**Comment by muesli4** [comment]
I updated https://github.com/muesli4/libwtk-sdl2.
